parameters:
    sidus_eav_model.context_manager.default_class: Sidus\EAVModelBundle\Context\ContextManager

services:
    sidus_eav_model.context.manager:
        class: '%sidus_eav_model.context_manager.default_class%'
        arguments:
            - '@form.factory'
            - '%sidus_eav_model.context.form_type%'
            - '%sidus_eav_model.context.default_context%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }
