services:
    sidus_eav_model.entity_manager:
        class: Doctrine\ORM\EntityManagerInterface
        factory: 'doctrine:getManagerForClass'
        arguments:
            - '%sidus_eav_model.entity.data.class%'

    # Warning, only use this service when you need the access to the entire EAV set
    Sidus\EAVModelBundle\Entity\DataRepository:
        class: Sidus\EAVModelBundle\Entity\DataRepository
        factory: 'sidus_eav_model.entity_manager:getRepository'
        arguments:
            - '%sidus_eav_model.entity.data.class%'

    Sidus\EAVModelBundle\Doctrine\EAVFinder:
        class: Sidus\EAVModelBundle\Doctrine\EAVFinder
        arguments:
            - '@sidus_eav_model.entity_manager'
            - '@Sidus\EAVModelBundle\Doctrine\DataLoaderInterface'

    Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager:
        class: Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager
        arguments:
            - '@doctrine'
